language: node_js
node_js:
  - "7.10"

branches:
  only:
    - master

before_script:
  - npm i -g firebase-tools
  - npm i -g

script:
  - audi build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
