language: node_js
node_js:
  - "7.10"

branches:
  only:
    - master

before_script:
  - npm i -g firebase-tools

script:
  - node scripts/build.js
  - cd functions && npm i

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
